package com.sgb.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.uaer_id
     *
     * @mbggenerated Thu Dec 23 15:44:08 CST 2021
     */
    private Integer uaerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_name
     *
     * @mbggenerated Thu Dec 23 15:44:08 CST 2021
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_pwd
     *
     * @mbggenerated Thu Dec 23 15:44:08 CST 2021
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.money
     *
     * @mbggenerated Thu Dec 23 15:44:08 CST 2021
     */
    private String money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.uaer_id
     *
     * @return the value of tb_user.uaer_id
     *
     * @mbggenerated Thu Dec 23 15:44:08 CST 2021
     */
    public Integer getUaerId() {
        return uaerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.uaer_id
     *
     * @param uaerId the value for tb_user.uaer_id
     *
     * @mbggenerated Thu Dec 23 15:44:08 CST 2021
     */
    public void setUaerId(Integer uaerId) {
        this.uaerId = uaerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_name
     *
     * @return the value of tb_user.user_name
     *
     * @mbggenerated Thu Dec 23 15:44:08 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_name
     *
     * @param userName the value for tb_user.user_name
     *
     * @mbggenerated Thu Dec 23 15:44:08 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_pwd
     *
     * @return the value of tb_user.user_pwd
     *
     * @mbggenerated Thu Dec 23 15:44:08 CST 2021
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_pwd
     *
     * @param userPwd the value for tb_user.user_pwd
     *
     * @mbggenerated Thu Dec 23 15:44:08 CST 2021
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.money
     *
     * @return the value of tb_user.money
     *
     * @mbggenerated Thu Dec 23 15:44:08 CST 2021
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.money
     *
     * @param money the value for tb_user.money
     *
     * @mbggenerated Thu Dec 23 15:44:08 CST 2021
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }
}